define(["require", "exports"], function (require, exports) {
    Object.defineProperty(exports, "__esModule", { value: true });

    exports.autocompletes = {



    

"Field":[],"Event":{"ServeAdResponseSignal":{"label":{"name":"ServeAdResponseSignal","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AdService/ServeAdResponseSignal)"]}},"VideoAdClosed":{"label":{"name":"VideoAdClosed","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AdService/VideoAdClosed)"]}},"PortalPrompt":{"label":{"name":"PortalPrompt","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AdService/PortalPrompt)"]}},"AdTeleportEnded":{"label":{"name":"AdTeleportEnded","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AdService/AdTeleportEnded)"]}},"ServeAdSignal":{"label":{"name":"ServeAdSignal","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AdService/ServeAdSignal)"]}},"ReportImpressionSignal":{"label":{"name":"ReportImpressionSignal","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AdService/ReportImpressionSignal)"]}},"AdTeleportInitiated":{"label":{"name":"AdTeleportInitiated","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AdService/AdTeleportInitiated)"]}},"ReportTeleportSignal":{"label":{"name":"ReportTeleportSignal","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AdService/ReportTeleportSignal)"]}}},"Method":{"GetAdTeleportInfo":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AdService/GetAdTeleportInfo)"]},"insertText":"GetAdTeleportInfo() \n\t\nend","label":{"name":"GetAdTeleportInfo","type":"(Function)"}},"ReturnToPublisherExperience":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AdService/ReturnToPublisherExperience)"]},"insertText":"ReturnToPublisherExperience(${1:adTeleportMethod}) \n\t\nend","label":{"name":"ReturnToPublisherExperience","type":"(Function)"}},"ShowVideoAd":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AdService/ShowVideoAd)"]},"insertText":"ShowVideoAd() \n\t\nend","label":{"name":"ShowVideoAd","type":"(Function)"}},"GetReportAdInfo":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AdService/GetReportAdInfo)"]},"insertText":"GetReportAdInfo() \n\t\nend","label":{"name":"GetReportAdInfo","type":"(Function)"}}},

__requires__: [['classes/Instance']],}})