define(["require", "exports"], function (require, exports) {
    Object.defineProperty(exports, "__esModule", { value: true });

    exports.autocompletes = {



    

"Field":{"WeightTarget":{"label":{"name":"WeightTarget","type":"(float)"}},"Animation":{"label":{"name":"Animation","type":"(Animation)"}},"Looped":{"label":{"name":"Looped","type":"(bool)"}},"TimePosition":{"label":{"name":"TimePosition","type":"(float)"}},"WeightCurrent":{"label":{"name":"WeightCurrent","type":"(float)"}},"IsPlaying":{"label":{"name":"IsPlaying","type":"(bool)"}},"Length":{"label":{"name":"Length","type":"(float)"}},"Speed":{"label":{"name":"Speed","type":"(float)"}},"Priority":{"label":{"name":"Priority","type":"(AnimationPriority)"}}},"Event":{"KeyframeReached":{"label":{"name":"KeyframeReached","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AnimationTrack/KeyframeReached)"]}},"Stopped":{"label":{"name":"Stopped","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AnimationTrack/Stopped)"]}},"Ended":{"label":{"name":"Ended","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AnimationTrack/Ended)"]}},"DidLoop":{"label":{"name":"DidLoop","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AnimationTrack/DidLoop)"]}}},"Method":{"AdjustWeight":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AnimationTrack/AdjustWeight)"]},"insertText":"AdjustWeight(${1:weight}, ${2:fadeTime}) \n\t\nend","label":{"name":"AdjustWeight","type":"(Function)"}},"GetTimeOfKeyframe":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AnimationTrack/GetTimeOfKeyframe)"]},"insertText":"GetTimeOfKeyframe(${1:keyframeName}) \n\t\nend","label":{"name":"GetTimeOfKeyframe","type":"(Function)"}},"Stop":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AnimationTrack/Stop)"]},"insertText":"Stop(${1:fadeTime}) \n\t\nend","label":{"name":"Stop","type":"(Function)"}},"Play":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AnimationTrack/Play)"]},"insertText":"Play(${1:fadeTime}, ${2:weight}, ${3:speed}) \n\t\nend","label":{"name":"Play","type":"(Function)"}},"GetMarkerReachedSignal":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AnimationTrack/GetMarkerReachedSignal)"]},"insertText":"GetMarkerReachedSignal(${1:name}) \n\t\nend","label":{"name":"GetMarkerReachedSignal","type":"(Function)"}},"AdjustSpeed":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AnimationTrack/AdjustSpeed)"]},"insertText":"AdjustSpeed(${1:speed}) \n\t\nend","label":{"name":"AdjustSpeed","type":"(Function)"}}},

__requires__: [['classes/Instance']],}})