define(["require", "exports"], function (require, exports) {
    Object.defineProperty(exports, "__esModule", { value: true });

    exports.autocompletes = {



    

"Field":[],"Event":[],"Method":{"GetAnimationClipById":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AnimationClipProvider/GetAnimationClipById)"]},"insertText":"GetAnimationClipById(${1:assetId}, ${2:useCache}) \n\t\nend","label":{"name":"GetAnimationClipById","type":"(Function)"}},"GetClipEvaluatorAsync":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AnimationClipProvider/GetClipEvaluatorAsync)"]},"insertText":"GetClipEvaluatorAsync(${1:assetId}) \n\t\nend","label":{"name":"GetClipEvaluatorAsync","type":"(Function)"}},"GetAnimations":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AnimationClipProvider/GetAnimations)"]},"insertText":"GetAnimations(${1:userId}) \n\t\nend","label":{"name":"GetAnimations","type":"(Function)"}},"RegisterActiveAnimationClip":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AnimationClipProvider/RegisterActiveAnimationClip)"]},"insertText":"RegisterActiveAnimationClip(${1:animationClip}) \n\t\nend","label":{"name":"RegisterActiveAnimationClip","type":"(Function)"}},"RegisterAnimationClip":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AnimationClipProvider/RegisterAnimationClip)"]},"insertText":"RegisterAnimationClip(${1:animationClip}) \n\t\nend","label":{"name":"RegisterAnimationClip","type":"(Function)"}},"GetAnimationClipAsync":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AnimationClipProvider/GetAnimationClipAsync)"]},"insertText":"GetAnimationClipAsync(${1:assetId}) \n\t\nend","label":{"name":"GetAnimationClipAsync","type":"(Function)"}},"GetAnimationClip":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AnimationClipProvider/GetAnimationClip)"]},"insertText":"GetAnimationClip(${1:assetId}) \n\t\nend","label":{"name":"GetAnimationClip","type":"(Function)"}},"GetMemStats":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AnimationClipProvider/GetMemStats)"]},"insertText":"GetMemStats() \n\t\nend","label":{"name":"GetMemStats","type":"(Function)"}}},

__requires__: [['classes/Instance']],}})