define(["require", "exports"], function (require, exports) {
    Object.defineProperty(exports, "__esModule", { value: true });

    exports.autocompletes = {



    

"Field":{"ClientFeaturesInitialized":{"label":{"name":"ClientFeaturesInitialized","type":"(bool)"}},"ServerFeatures":{"label":{"name":"ServerFeatures","type":"(int)"}},"ClientFeatures":{"label":{"name":"ClientFeatures","type":"(int)"}}},"Event":{"OnClientFeatures":{"label":{"name":"OnClientFeatures","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AvatarChatService/OnClientFeatures)"]}}},"Method":{"IsEnabled":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AvatarChatService/IsEnabled)"]},"insertText":"IsEnabled(${1:mask}, ${2:feature}) \n\t\nend","label":{"name":"IsEnabled","type":"(Function)"}},"IsPlaceEnabled":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AvatarChatService/IsPlaceEnabled)"]},"insertText":"IsPlaceEnabled() \n\t\nend","label":{"name":"IsPlaceEnabled","type":"(Function)"}},"GetClientFeaturesAsync":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AvatarChatService/GetClientFeaturesAsync)"]},"insertText":"GetClientFeaturesAsync() \n\t\nend","label":{"name":"GetClientFeaturesAsync","type":"(Function)"}},"IsUniverseEnabled":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AvatarChatService/IsUniverseEnabled)"]},"insertText":"IsUniverseEnabled() \n\t\nend","label":{"name":"IsUniverseEnabled","type":"(Function)"}},"PollServerFeatures":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AvatarChatService/PollServerFeatures)"]},"insertText":"PollServerFeatures() \n\t\nend","label":{"name":"PollServerFeatures","type":"(Function)"}},"GetServerFeaturesAsync":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AvatarChatService/GetServerFeaturesAsync)"]},"insertText":"GetServerFeaturesAsync() \n\t\nend","label":{"name":"GetServerFeaturesAsync","type":"(Function)"}},"PollClientFeatures":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/AvatarChatService/PollClientFeatures)"]},"insertText":"PollClientFeatures() \n\t\nend","label":{"name":"PollClientFeatures","type":"(Function)"}}},

__requires__: [['classes/Instance']],}})