define(["require", "exports"], function (require, exports) {
    Object.defineProperty(exports, "__esModule", { value: true });

    exports.autocompletes = {



    

"Field":[],"Event":{"BadgeAwarded":{"label":{"name":"BadgeAwarded","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/BadgeService/BadgeAwarded)"]}},"OnBadgeAwarded":{"label":{"name":"OnBadgeAwarded","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/BadgeService/OnBadgeAwarded)"]}}},"Method":{"GetBadgeInfoAsync":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/BadgeService/GetBadgeInfoAsync)"]},"insertText":"GetBadgeInfoAsync(${1:badgeId}) \n\t\nend","label":{"name":"GetBadgeInfoAsync","type":"(Function)"}},"IsDisabled":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/BadgeService/IsDisabled)"]},"insertText":"IsDisabled(${1:badgeId}) \n\t\nend","label":{"name":"IsDisabled","type":"(Function)"}},"AwardBadge":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/BadgeService/AwardBadge)"]},"insertText":"AwardBadge(${1:userId}, ${2:badgeId}) \n\t\nend","label":{"name":"AwardBadge","type":"(Function)"}},"UserHasBadgeAsync":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/BadgeService/UserHasBadgeAsync)"]},"insertText":"UserHasBadgeAsync(${1:userId}, ${2:badgeId}) \n\t\nend","label":{"name":"UserHasBadgeAsync","type":"(Function)"}},"IsLegal":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/BadgeService/IsLegal)"]},"insertText":"IsLegal(${1:badgeId}) \n\t\nend","label":{"name":"IsLegal","type":"(Function)"}},"UserHasBadge":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/BadgeService/UserHasBadge)"]},"insertText":"UserHasBadge(${1:userId}, ${2:badgeId}) \n\t\nend","label":{"name":"UserHasBadge","type":"(Function)"}}},

__requires__: [['classes/Instance']],}})