define(["require", "exports"], function (require, exports) {
    Object.defineProperty(exports, "__esModule", { value: true });

    exports.autocompletes = {



    

"Field":{"ImageData":{"label":{"name":"ImageData","type":"(BinaryString)"}},"Size":{"label":{"name":"Size","type":"(Vector2)"}}},"Event":[],"Method":{"DrawLine":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/EditableImage/DrawLine)"]},"insertText":"DrawLine(${1:p1}, ${2:p2}, ${3:color}, ${4:transparency}) \n\t\nend","label":{"name":"DrawLine","type":"(Function)"}},"DrawImage":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/EditableImage/DrawImage)"]},"insertText":"DrawImage(${1:position}, ${2:image}, ${3:combineType}) \n\t\nend","label":{"name":"DrawImage","type":"(Function)"}},"DrawCircle":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/EditableImage/DrawCircle)"]},"insertText":"DrawCircle(${1:center}, ${2:radius}, ${3:color}, ${4:transparency}) \n\t\nend","label":{"name":"DrawCircle","type":"(Function)"}},"Crop":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/EditableImage/Crop)"]},"insertText":"Crop(${1:min}, ${2:max}) \n\t\nend","label":{"name":"Crop","type":"(Function)"}},"Copy":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/EditableImage/Copy)"]},"insertText":"Copy(${1:min}, ${2:max}) \n\t\nend","label":{"name":"Copy","type":"(Function)"}},"WritePixels":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/EditableImage/WritePixels)"]},"insertText":"WritePixels(${1:position}, ${2:size}, ${3:pixels}) \n\t\nend","label":{"name":"WritePixels","type":"(Function)"}},"ReadPixels":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/EditableImage/ReadPixels)"]},"insertText":"ReadPixels(${1:position}, ${2:size}) \n\t\nend","label":{"name":"ReadPixels","type":"(Function)"}},"DrawRectangle":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/EditableImage/DrawRectangle)"]},"insertText":"DrawRectangle(${1:position}, ${2:size}, ${3:color}, ${4:transparency}) \n\t\nend","label":{"name":"DrawRectangle","type":"(Function)"}},"Resize":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/EditableImage/Resize)"]},"insertText":"Resize(${1:size}) \n\t\nend","label":{"name":"Resize","type":"(Function)"}},"Rotate":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/EditableImage/Rotate)"]},"insertText":"Rotate(${1:degrees}, ${2:changeSize}) \n\t\nend","label":{"name":"Rotate","type":"(Function)"}}},

__requires__: [['classes/Instance']],}})