define(["require", "exports"], function (require, exports) {
    Object.defineProperty(exports, "__esModule", { value: true });

    exports.autocompletes = {



    

"Field":{"AudioAnimationEnabled":{"label":{"name":"AudioAnimationEnabled","type":"(bool)"}},"VideoAnimationEnabled":{"label":{"name":"VideoAnimationEnabled","type":"(bool)"}},"FlipHeadOrientation":{"label":{"name":"FlipHeadOrientation","type":"(bool)"}},"FaceTrackingStatusEnum":{"label":{"name":"FaceTrackingStatusEnum","type":"(TrackerFaceTrackingStatus)"}}},"Event":{"TrackerError":{"label":{"name":"TrackerError","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/FaceAnimatorService/TrackerError)"]}},"TrackerPrompt":{"label":{"name":"TrackerPrompt","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/FaceAnimatorService/TrackerPrompt)"]}}},"Method":{"IsStarted":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/FaceAnimatorService/IsStarted)"]},"insertText":"IsStarted() \n\t\nend","label":{"name":"IsStarted","type":"(Function)"}},"Stop":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/FaceAnimatorService/Stop)"]},"insertText":"Stop() \n\t\nend","label":{"name":"Stop","type":"(Function)"}},"Init":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/FaceAnimatorService/Init)"]},"insertText":"Init(${1:videoEnabled}, ${2:audioEnabled}) \n\t\nend","label":{"name":"Init","type":"(Function)"}},"Start":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/FaceAnimatorService/Start)"]},"insertText":"Start() \n\t\nend","label":{"name":"Start","type":"(Function)"}},"Step":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/FaceAnimatorService/Step)"]},"insertText":"Step() \n\t\nend","label":{"name":"Step","type":"(Function)"}},"GetTrackerLodController":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/FaceAnimatorService/GetTrackerLodController)"]},"insertText":"GetTrackerLodController() \n\t\nend","label":{"name":"GetTrackerLodController","type":"(Function)"}}},

__requires__: [['classes/Instance']],}})