define(["require", "exports"], function (require, exports) {
    Object.defineProperty(exports, "__esModule", { value: true });

    exports.autocompletes = {



    

"Field":{"MouseButton2DownConnectionCount":{"label":{"name":"MouseButton2DownConnectionCount","type":"(int)"}},"MouseButton2UpConnectionCount":{"label":{"name":"MouseButton2UpConnectionCount","type":"(int)"}},"Modal":{"label":{"name":"Modal","type":"(bool)"}},"MouseButton1DownConnectionCount":{"label":{"name":"MouseButton1DownConnectionCount","type":"(int)"}},"MouseButton1ClickConnectionCount":{"label":{"name":"MouseButton1ClickConnectionCount","type":"(int)"}},"AutoButtonColor":{"label":{"name":"AutoButtonColor","type":"(bool)"}},"Style":{"label":{"name":"Style","type":"(ButtonStyle)"}},"Selected":{"label":{"name":"Selected","type":"(bool)"}},"MouseButton2ClickConnectionCount":{"label":{"name":"MouseButton2ClickConnectionCount","type":"(int)"}},"MouseButton1UpConnectionCount":{"label":{"name":"MouseButton1UpConnectionCount","type":"(int)"}}},"Event":{"MouseButton1Down":{"label":{"name":"MouseButton1Down","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/GuiButton/MouseButton1Down)"]}},"MouseButton1Click":{"label":{"name":"MouseButton1Click","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/GuiButton/MouseButton1Click)"]}},"MouseButton2Up":{"label":{"name":"MouseButton2Up","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/GuiButton/MouseButton2Up)"]}},"MouseButton2Click":{"label":{"name":"MouseButton2Click","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/GuiButton/MouseButton2Click)"]}},"MouseButton2Down":{"label":{"name":"MouseButton2Down","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/GuiButton/MouseButton2Down)"]}},"Activated":{"label":{"name":"Activated","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/GuiButton/Activated)"]}},"MouseButton1Up":{"label":{"name":"MouseButton1Up","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/GuiButton/MouseButton1Up)"]}}},"Method":[],

__requires__: [['classes/Instance']],}})