define(["require", "exports"], function (require, exports) {
    Object.defineProperty(exports, "__esModule", { value: true });

    exports.autocompletes = {



    

"Field":[],"Event":{"ProgressUpdate":{"label":{"name":"ProgressUpdate","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/HeightmapImporterService/ProgressUpdate)"]}},"ColormapHasUnknownPixels":{"label":{"name":"ColormapHasUnknownPixels","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/HeightmapImporterService/ColormapHasUnknownPixels)"]}}},"Method":{"GetHeightmapPreviewAsync":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/HeightmapImporterService/GetHeightmapPreviewAsync)"]},"insertText":"GetHeightmapPreviewAsync(${1:heightmapAssetId}) \n\t\nend","label":{"name":"GetHeightmapPreviewAsync","type":"(Function)"}},"SetImportHeightmapPaused":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/HeightmapImporterService/SetImportHeightmapPaused)"]},"insertText":"SetImportHeightmapPaused(${1:paused}) \n\t\nend","label":{"name":"SetImportHeightmapPaused","type":"(Function)"}},"IsValidColormap":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/HeightmapImporterService/IsValidColormap)"]},"insertText":"IsValidColormap(${1:colormapAssetId}) \n\t\nend","label":{"name":"IsValidColormap","type":"(Function)"}},"CancelImportHeightmap":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/HeightmapImporterService/CancelImportHeightmap)"]},"insertText":"CancelImportHeightmap() \n\t\nend","label":{"name":"CancelImportHeightmap","type":"(Function)"}},"ImportHeightmap":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/HeightmapImporterService/ImportHeightmap)"]},"insertText":"ImportHeightmap(${1:region}, ${2:heightmapAssetId}, ${3:colormapAssetId}, ${4:defaultMaterial}) \n\t\nend","label":{"name":"ImportHeightmap","type":"(Function)"}},"IsValidHeightmap":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/HeightmapImporterService/IsValidHeightmap)"]},"insertText":"IsValidHeightmap(${1:heightmapAssetId}) \n\t\nend","label":{"name":"IsValidHeightmap","type":"(Function)"}}},

__requires__: [['classes/Instance']],}})