define(["require", "exports"], function (require, exports) {
    Object.defineProperty(exports, "__esModule", { value: true });

    exports.autocompletes = {



    

"Field":{"ServerLiveEditingMode":{"label":{"name":"ServerLiveEditingMode","type":"(ServerLiveEditingMode)"}}},"Event":{"BroadcastMessage":{"label":{"name":"BroadcastMessage","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/LiveScriptingService/BroadcastMessage)"]}},"FailedToOpen":{"label":{"name":"FailedToOpen","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/LiveScriptingService/FailedToOpen)"]}},"EndEdit":{"label":{"name":"EndEdit","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/LiveScriptingService/EndEdit)"]}},"KickFromEdit":{"label":{"name":"KickFromEdit","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/LiveScriptingService/KickFromEdit)"]}},"SendOperation":{"label":{"name":"SendOperation","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/LiveScriptingService/SendOperation)"]}},"LiveEditingClientConfiguration":{"label":{"name":"LiveEditingClientConfiguration","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/LiveScriptingService/LiveEditingClientConfiguration)"]}},"BeginEdit":{"label":{"name":"BeginEdit","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/LiveScriptingService/BeginEdit)"]}},"SendAtomicOperation":{"label":{"name":"SendAtomicOperation","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/LiveScriptingService/SendAtomicOperation)"]}},"SendAtomicUpdateResponse":{"label":{"name":"SendAtomicUpdateResponse","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/LiveScriptingService/SendAtomicUpdateResponse)"]}},"OpenedWithSource":{"label":{"name":"OpenedWithSource","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/LiveScriptingService/OpenedWithSource)"]}}},"Method":[],

__requires__: [['classes/Instance']],}})