define(["require", "exports"], function (require, exports) {
    Object.defineProperty(exports, "__esModule", { value: true });

    exports.autocompletes = {



    

"Field":{"Enabled":{"label":{"name":"Enabled","type":"(bool)"}},"RemoveOnHit":{"label":{"name":"RemoveOnHit","type":"(bool)"}},"Script":{"label":{"name":"Script","type":"(string)"}},"ContinueExecution":{"label":{"name":"ContinueExecution","type":"(bool)"}},"Id":{"label":{"name":"Id","type":"(int)"}},"Condition":{"label":{"name":"Condition","type":"(string)"}},"Line":{"label":{"name":"Line","type":"(int)"}},"LogMessage":{"label":{"name":"LogMessage","type":"(string)"}},"Valid":{"label":{"name":"Valid","type":"(bool)"}},"IsLogpoint":{"label":{"name":"IsLogpoint","type":"(bool)"}}},"Event":[],"Method":{"SetChildBreakpointEnabledByScriptAndContext":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/MetaBreakpoint/SetChildBreakpointEnabledByScriptAndContext)"]},"insertText":"SetChildBreakpointEnabledByScriptAndContext(${1:script}, ${2:contextGST}, ${3:enabled}) \n\t\nend","label":{"name":"SetChildBreakpointEnabledByScriptAndContext","type":"(Function)"}},"Remove":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/MetaBreakpoint/Remove)"]},"insertText":"Remove(${1:status}) \n\t\nend","label":{"name":"Remove","type":"(Function)"}},"SetRemoveOnHit":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/MetaBreakpoint/SetRemoveOnHit)"]},"insertText":"SetRemoveOnHit(${1:enabled}) \n\t\nend","label":{"name":"SetRemoveOnHit","type":"(Function)"}},"SetLine":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/MetaBreakpoint/SetLine)"]},"insertText":"SetLine(${1:line}, ${2:status}) \n\t\nend","label":{"name":"SetLine","type":"(Function)"}},"SetContextEnabled":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/MetaBreakpoint/SetContextEnabled)"]},"insertText":"SetContextEnabled(${1:context}, ${2:enabled}) \n\t\nend","label":{"name":"SetContextEnabled","type":"(Function)"}},"SetEnabled":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/MetaBreakpoint/SetEnabled)"]},"insertText":"SetEnabled(${1:enabled}) \n\t\nend","label":{"name":"SetEnabled","type":"(Function)"}},"SetContinueExecution":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/MetaBreakpoint/SetContinueExecution)"]},"insertText":"SetContinueExecution(${1:enabled}) \n\t\nend","label":{"name":"SetContinueExecution","type":"(Function)"}},"GetContextBreakpoints":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/MetaBreakpoint/GetContextBreakpoints)"]},"insertText":"GetContextBreakpoints() \n\t\nend","label":{"name":"GetContextBreakpoints","type":"(Function)"}}},

__requires__: [['classes/Instance']],}})