define(["require", "exports"], function (require, exports) {
    Object.defineProperty(exports, "__esModule", { value: true });

    exports.autocompletes = {



    

"Field":{"Origin":{"label":{"name":"Origin","type":"(CFrame)"}},"target":{"label":{"name":"target","type":"(BasePart)"}},"hit":{"label":{"name":"hit","type":"(CFrame)"}},"Y":{"label":{"name":"Y","type":"(int)"}},"X":{"label":{"name":"X","type":"(int)"}},"ViewSizeX":{"label":{"name":"ViewSizeX","type":"(int)"}},"TargetFilter":{"label":{"name":"TargetFilter","type":"(Instance)"}},"ViewSizeY":{"label":{"name":"ViewSizeY","type":"(int)"}},"Hit":{"label":{"name":"Hit","type":"(CFrame)"}},"Target":{"label":{"name":"Target","type":"(BasePart)"}},"UnitRay":{"label":{"name":"UnitRay","type":"(Ray)"}},"Icon":{"label":{"name":"Icon","type":"(Content)"}},"TargetSurface":{"label":{"name":"TargetSurface","type":"(NormalId)"}}},"Event":{"KeyUp":{"label":{"name":"KeyUp","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/Mouse/KeyUp)"]}},"Idle":{"label":{"name":"Idle","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/Mouse/Idle)"]}},"keyDown":{"label":{"name":"keyDown","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/Mouse/keyDown)"]}},"WheelForward":{"label":{"name":"WheelForward","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/Mouse/WheelForward)"]}},"Move":{"label":{"name":"Move","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/Mouse/Move)"]}},"WheelBackward":{"label":{"name":"WheelBackward","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/Mouse/WheelBackward)"]}},"Button1Down":{"label":{"name":"Button1Down","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/Mouse/Button1Down)"]}},"Button2Down":{"label":{"name":"Button2Down","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/Mouse/Button2Down)"]}},"Button1Up":{"label":{"name":"Button1Up","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/Mouse/Button1Up)"]}},"Button2Up":{"label":{"name":"Button2Up","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/Mouse/Button2Up)"]}},"KeyDown":{"label":{"name":"KeyDown","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/Mouse/KeyDown)"]}}},"Method":[],

__requires__: [['classes/Instance']],}})