define(["require", "exports"], function (require, exports) {
    Object.defineProperty(exports, "__esModule", { value: true });

    exports.autocompletes = {



    

"Field":{"Thickness":{"label":{"name":"Thickness","type":"(float)"}},"AbsoluteSize":{"label":{"name":"AbsoluteSize","type":"(Vector2)"}},"Position":{"label":{"name":"Position","type":"(UDim2)"}},"Color":{"label":{"name":"Color","type":"(Color3)"}},"Visible":{"label":{"name":"Visible","type":"(bool)"}},"Transparency":{"label":{"name":"Transparency","type":"(float)"}},"SelectedControlPoint":{"label":{"name":"SelectedControlPoint","type":"(int)"}}},"Event":[],"Method":{"GetSegmentCount":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/Path2D/GetSegmentCount)"]},"insertText":"GetSegmentCount() \n\t\nend","label":{"name":"GetSegmentCount","type":"(Function)"}},"GetPositionOnCurve":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/Path2D/GetPositionOnCurve)"]},"insertText":"GetPositionOnCurve(${1:t}) \n\t\nend","label":{"name":"GetPositionOnCurve","type":"(Function)"}},"GetControlPoints":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/Path2D/GetControlPoints)"]},"insertText":"GetControlPoints() \n\t\nend","label":{"name":"GetControlPoints","type":"(Function)"}},"GetPositionOnCurveArcLength":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/Path2D/GetPositionOnCurveArcLength)"]},"insertText":"GetPositionOnCurveArcLength(${1:t}) \n\t\nend","label":{"name":"GetPositionOnCurveArcLength","type":"(Function)"}},"SetControlPoints":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/Path2D/SetControlPoints)"]},"insertText":"SetControlPoints(${1:controlPoints}) \n\t\nend","label":{"name":"SetControlPoints","type":"(Function)"}},"GetTangentOnCurve":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/Path2D/GetTangentOnCurve)"]},"insertText":"GetTangentOnCurve(${1:t}) \n\t\nend","label":{"name":"GetTangentOnCurve","type":"(Function)"}},"GetTangentOnCurveArcLength":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/Path2D/GetTangentOnCurveArcLength)"]},"insertText":"GetTangentOnCurveArcLength(${1:t}) \n\t\nend","label":{"name":"GetTangentOnCurveArcLength","type":"(Function)"}}},

__requires__: [['classes/Instance']],}})