define(["require", "exports"], function (require, exports) {
    Object.defineProperty(exports, "__esModule", { value: true });

    exports.autocompletes = {



    

"Field":{"ScrollVelocity":{"label":{"name":"ScrollVelocity","type":"(Vector2)"}},"AutomaticCanvasSize":{"label":{"name":"AutomaticCanvasSize","type":"(AutomaticSize)"}},"AbsoluteWindowSize":{"label":{"name":"AbsoluteWindowSize","type":"(Vector2)"}},"ScrollingDirection":{"label":{"name":"ScrollingDirection","type":"(ScrollingDirection)"}},"AbsoluteCanvasSize":{"label":{"name":"AbsoluteCanvasSize","type":"(Vector2)"}},"CanvasSize":{"label":{"name":"CanvasSize","type":"(UDim2)"}},"ScrollBarImageColor3":{"label":{"name":"ScrollBarImageColor3","type":"(Color3)"}},"MidImage":{"label":{"name":"MidImage","type":"(Content)"}},"VerticalBarRect":{"label":{"name":"VerticalBarRect","type":"(Rect)"}},"HorizontalBarRect":{"label":{"name":"HorizontalBarRect","type":"(Rect)"}},"ScrollBarImageTransparency":{"label":{"name":"ScrollBarImageTransparency","type":"(float)"}},"CanvasPosition":{"label":{"name":"CanvasPosition","type":"(Vector2)"}},"MaxCanvasPosition":{"label":{"name":"MaxCanvasPosition","type":"(Vector2)"}},"ElasticBehavior":{"label":{"name":"ElasticBehavior","type":"(ElasticBehavior)"}},"VerticalScrollBarPosition":{"label":{"name":"VerticalScrollBarPosition","type":"(VerticalScrollBarPosition)"}},"TopImage":{"label":{"name":"TopImage","type":"(Content)"}},"VerticalScrollBarInset":{"label":{"name":"VerticalScrollBarInset","type":"(ScrollBarInset)"}},"ScrollingEnabled":{"label":{"name":"ScrollingEnabled","type":"(bool)"}},"BottomImage":{"label":{"name":"BottomImage","type":"(Content)"}},"ScrollBarThickness":{"label":{"name":"ScrollBarThickness","type":"(int)"}},"HorizontalScrollBarInset":{"label":{"name":"HorizontalScrollBarInset","type":"(ScrollBarInset)"}}},"Event":[],"Method":{"ClearInertialScrolling":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/ScrollingFrame/ClearInertialScrolling)"]},"insertText":"ClearInertialScrolling() \n\t\nend","label":{"name":"ClearInertialScrolling","type":"(Function)"}},"ScrollToTop":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/ScrollingFrame/ScrollToTop)"]},"insertText":"ScrollToTop() \n\t\nend","label":{"name":"ScrollToTop","type":"(Function)"}},"GetSampledInertialVelocity":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/ScrollingFrame/GetSampledInertialVelocity)"]},"insertText":"GetSampledInertialVelocity() \n\t\nend","label":{"name":"GetSampledInertialVelocity","type":"(Function)"}}},

__requires__: [['classes/Instance']],}})