define(["require", "exports"], function (require, exports) {
    Object.defineProperty(exports, "__esModule", { value: true });

    exports.autocompletes = {



    

"Field":{"VirtualCursorMode":{"label":{"name":"VirtualCursorMode","type":"(VirtualCursorMode)"}},"ShowDevelopmentGui":{"label":{"name":"ShowDevelopmentGui","type":"(bool)"}},"ScreenOrientation":{"label":{"name":"ScreenOrientation","type":"(ScreenOrientation)"}},"RtlTextSupport":{"label":{"name":"RtlTextSupport","type":"(RtlTextSupport)"}},"ProcessUserInput":{"label":{"name":"ProcessUserInput","type":"(bool)"}},"ResetPlayerGuiOnSpawn":{"label":{"name":"ResetPlayerGuiOnSpawn","type":"(bool)"}}},"Event":{"CoreGuiChangedSignal":{"label":{"name":"CoreGuiChangedSignal","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/StarterGui/CoreGuiChangedSignal)"]}}},"Method":{"SetCoreGuiEnabled":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/StarterGui/SetCoreGuiEnabled)"]},"insertText":"SetCoreGuiEnabled(${1:coreGuiType}, ${2:enabled}) \n\t\nend","label":{"name":"SetCoreGuiEnabled","type":"(Function)"}},"RegisterGetCore":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/StarterGui/RegisterGetCore)"]},"insertText":"RegisterGetCore(${1:parameterName}, ${2:getFunction}) \n\t\nend","label":{"name":"RegisterGetCore","type":"(Function)"}},"GetCoreGuiEnabled":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/StarterGui/GetCoreGuiEnabled)"]},"insertText":"GetCoreGuiEnabled(${1:coreGuiType}) \n\t\nend","label":{"name":"GetCoreGuiEnabled","type":"(Function)"}},"GetCore":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/StarterGui/GetCore)"]},"insertText":"GetCore(${1:parameterName}) \n\t\nend","label":{"name":"GetCore","type":"(Function)"}},"SetCore":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/StarterGui/SetCore)"]},"insertText":"SetCore(${1:parameterName}, ${2:value}) \n\t\nend","label":{"name":"SetCore","type":"(Function)"}},"RegisterSetCore":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/StarterGui/RegisterSetCore)"]},"insertText":"RegisterSetCore(${1:parameterName}, ${2:setFunction}) \n\t\nend","label":{"name":"RegisterSetCore","type":"(Function)"}}},

__requires__: [['classes/Instance']],}})