define(["require", "exports"], function (require, exports) {
    Object.defineProperty(exports, "__esModule", { value: true });

    exports.autocompletes = {



    

"Field":{"Enabled":{"label":{"name":"Enabled","type":"(bool)"}},"RequiresHandle":{"label":{"name":"RequiresHandle","type":"(bool)"}},"GripPos":{"label":{"name":"GripPos","type":"(Vector3)"}},"Grip":{"label":{"name":"Grip","type":"(CFrame)"}},"GripUp":{"label":{"name":"GripUp","type":"(Vector3)"}},"CanBeDropped":{"label":{"name":"CanBeDropped","type":"(bool)"}},"ToolTip":{"label":{"name":"ToolTip","type":"(string)"}},"GripForward":{"label":{"name":"GripForward","type":"(Vector3)"}},"ManualActivationOnly":{"label":{"name":"ManualActivationOnly","type":"(bool)"}},"GripRight":{"label":{"name":"GripRight","type":"(Vector3)"}}},"Event":{"Deactivated":{"label":{"name":"Deactivated","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/Tool/Deactivated)"]}},"Unequipped":{"label":{"name":"Unequipped","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/Tool/Unequipped)"]}},"VRLaserPointerClicked":{"label":{"name":"VRLaserPointerClicked","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/Tool/VRLaserPointerClicked)"]}},"Activated":{"label":{"name":"Activated","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/Tool/Activated)"]}},"Equipped":{"label":{"name":"Equipped","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/Tool/Equipped)"]}}},"Method":{"Deactivate":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/Tool/Deactivate)"]},"insertText":"Deactivate() \n\t\nend","label":{"name":"Deactivate","type":"(Function)"}},"Activate":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/Tool/Activate)"]},"insertText":"Activate() \n\t\nend","label":{"name":"Activate","type":"(Function)"}}},

__requires__: [['classes/Instance']],}})