define(["require", "exports"], function (require, exports) {
    Object.defineProperty(exports, "__esModule", { value: true });

    exports.autocompletes = {



    

"Field":{"TimePositionReplicating":{"label":{"name":"TimePositionReplicating","type":"(double)"}},"IsLoaded":{"label":{"name":"IsLoaded","type":"(bool)"}},"TimeLength":{"label":{"name":"TimeLength","type":"(double)"}},"Resolution":{"label":{"name":"Resolution","type":"(Vector2)"}},"Video":{"label":{"name":"Video","type":"(Content)"}},"Volume":{"label":{"name":"Volume","type":"(float)"}},"TimePosition":{"label":{"name":"TimePosition","type":"(double)"}},"Looped":{"label":{"name":"Looped","type":"(bool)"}},"PlayingReplicating":{"label":{"name":"PlayingReplicating","type":"(bool)"}},"Playing":{"label":{"name":"Playing","type":"(bool)"}}},"Event":{"Played":{"label":{"name":"Played","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/VideoFrame/Played)"]}},"Paused":{"label":{"name":"Paused","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/VideoFrame/Paused)"]}},"DidLoop":{"label":{"name":"DidLoop","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/VideoFrame/DidLoop)"]}},"Loaded":{"label":{"name":"Loaded","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/VideoFrame/Loaded)"]}},"TimePositionUpdatedFromServer":{"label":{"name":"TimePositionUpdatedFromServer","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/VideoFrame/TimePositionUpdatedFromServer)"]}},"PlayingUpdatedFromServer":{"label":{"name":"PlayingUpdatedFromServer","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/VideoFrame/PlayingUpdatedFromServer)"]}},"Ended":{"label":{"name":"Ended","type":"(RBXScriptSignal)"},"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/VideoFrame/Ended)"]}}},"Method":{"Pause":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/VideoFrame/Pause)"]},"insertText":"Pause() \n\t\nend","label":{"name":"Pause","type":"(Function)"}},"Play":{"documentation":{"value":["[View documentation](https://developer.roblox.com/en-us/api-reference/events/VideoFrame/Play)"]},"insertText":"Play() \n\t\nend","label":{"name":"Play","type":"(Function)"}}},

__requires__: [['classes/Instance']],}})